#!/usr/bin/env bash -e

core=./Bin/RentalOffer.Core.dll
json=./Lib/Json60r3/Bin/Net45/Newtonsoft.Json.dll

mkdir -p ./Bin

gmcs -t:library -r:$json -out:$core RentalOffer.Core/*.cs
gmcs -t:exe -r:$core -out:./Bin/Monitor.exe RentalOffer.Monitor/*.cs
gmcs -t:exe -r:$core -out:./Bin/Need.exe RentalOffer.Need/*.cs

cp $json ./Bin

echo Build successful
