#!/usr/bin/env bash

deps=(
./Lib/Json60r3/Bin/Net45/Newtonsoft.Json.dll
./Lib/rabbitmq-dotnet-client-3.3.1-dotnet-3.0/bin/RabbitMQ.Client.dll
)

function join { local IFS="$1"; shift; echo "$*"; } && export join

mkdir -p ./Bin
for i in "${deps[@]}"
do
    cp $i ./Bin
done

refs=$(join , "${deps[@]}")
